### ISSUE TITLE
请问前端题目界面在哪儿

### ISSUE THREAD

**Issue by ISheepp** [cijee/siseoj#1]
你好，我刚刚在我本地部署了你的项目，请问是暂时只有后台管理的界面吗

**Comment by jeesoner** [comment]
> 你好，我刚刚在我本地部署了你的项目，请问是暂时只有后台管理的界面吗

是的，现在还在开发中，许多功能都还没做好

**Comment by ISheepp** [comment]
> > 你好，我刚刚在我本地部署了你的项目，请问是暂时只有后台管理的界面吗
> 
> 是的，现在还在开发中，许多功能都还没做好

好的，你做的很酷👍
